  datasets_dir: "../datasets/"
  save_dir: "../test_saves/"
  
  model_options:
    - SVM
    - KNN
    - LR
    - RF
    - DT
    - NB
    - GBC
    - ABC
    - EC


  cat_cols: ["sex","exng","caa","cp","fbs","restecg","slp","thall"]
  con_cols: ["age","trtbps","chol","thalachh","oldpeak"]